### PR TITLE
Added more HEX parsing support

### PR DESCRIPTION
**Pull request by nadavshatz**
Support for 3 letter hex.
Support for # at the beginning.
Added relevant specs.
Updated HSL spec to correct values.

Solves https://github.com/jordanstephens/paleta/issues/6

### CODE REVIEW

**Comment by jordanstephens** [comment]
Thanks for working on this Nadav!

Can we get a PR that doesn't include the quote changes? I tend to agree with [Github's Ruby Styleguide](https://github.com/styleguide/ruby) on favoring double-quoted strings over single-quoted strings. There are places where this is inconsistent in paleta (this code is three years old), but I am more interested in moving in the direction of favoring double-quotes in general.

I think everything else looks okay.

**Comment by nadavshatz** [comment]
Thanks for the comments and speedy reply Jordan!

Can we add Circle-CI support? It will just be nice to have all the pull requests automatically checked. And it's free and super fast for open source repos.

**Comment by jordanstephens** [comment]
This looks great; thank you! Do you mind squashing these commits into one before I merge?

I'm totally supportive of integrating CI into this repo. I've been using TravisCI on other repos, any reason to use Circle over Travis?

**Comment by nadavshatz** [comment]
Squashed!

I've found Circe-ci to be a bit faster and have less queueing but with travis we can have multiple ruby versions (not sure if circle support that). Either is totally fine. Just having one would be nice. We can also add CodeClimate and Gemnasium if you want, both give some insight into the health of the project.
If we add CodeClimate I can add code coverage support as well.

**Comment by lbain** [comment]
Wow, that was crazy fast! Thanks so much for working on it :)

**Comment by lbain** [comment]
@jordanstephens any chance this could get merged? I'd *love* to use it :)

**Comment by jordanstephens** [comment]
Merged!

I'll get a new version out right away, and I'll get us set up with some CI as well.

Thanks @nadavshatz and @lbain, great work!

**Comment by nadavshatz** [comment]
@jordanstephens no problem!
@lbain Thanks for bringing this up!

**Comment by lbain** [comment]
YaY! Thanks very much @nadavshatz for the fix, and @jordanstephens for getting it merged in :)

**Pull request merged**
