### PR TITLE
Better Jruby support

### PR DESCRIPTION
**Pull request by nadavshatz**
Made some changes and fixes to accommodate development and usage on both Jruby and normal ruby.
The tests are passing for me locally which makes me think this is an issue with the JVM and the math implementation. Not so sure what to do about it, any ideas?

Take a look and let me know what you think.

I branched out of your new branch so it won't conflict once that one is merged.

### CODE REVIEW

**Comment by jordanstephens** [comment]
Hmm, yeah I'm seeing passing specs locally with that same version of jruby. I've got java 1.8 running locally, and it looks like the travis VM is running 1.7, _maybe_ that's related. I'm not sure though. I'm going to see if I can figure anything else out.

**Comment by jordanstephens** [comment]
Okay @nadavshatz, I just ran the specs on another machine with java 1.7 and I'm seeing the same failing spec. I'm still not sure _why_ exactly, but it's definitely starting to smell like it's related to java 1.7

**Comment by jordanstephens** [comment]
I still don't know why its off by one with Java 7, but I just found out how to tell travis to use Java 8, so I say we roll with that for now. If anyone wants to take the time to figure out what's up on Java 7, that's fine, but I don't think it's worth the effort for me personally right now.

Going to go ahead and merge this

**Comment by jordanstephens** [comment]
Thanks for leading on this @nadavshatz

**Comment by nadavshatz** [comment]
@jordanstephens No problem!

**Pull request merged**
